name: rsmpi Testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  test:
    name: Test rsmpi
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - windows-latest
          - ubuntu-latest
          - macos-latest
        rust:
          - 1.36.0 # First version with MaybeUninit
          - stable
          - nightly
    steps:
      - name: Install LLVM (Ubuntu)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y llvm-10-dev
      - name: Clang Version
        run: clang --version
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
      - name: Rust Version
        run: rustc +${{matrix.rust}} --version
