name: rsmpi Testing
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
defaults:
  run:
    shell: bash
jobs:
  test:
    name: Test rsmpi
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust == 'nightly' }}
    strategy:
      fail-fast: false
      matrix:
        os: 
          - windows-latest
          - ubuntu-latest
          - macos-latest
        rust:
          - 1.36.0 # First version with MaybeUninit
          - stable
          - nightly
    steps:
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
      - name: Rust Version
        run: rustc +${{matrix.rust}} --version
